### ISSUE TITLE
Need clean project otherwise will output old words

### ISSUE THREAD

**Issue by nxnyk** [LikeTheSalad/android-stem#46] opened 2023-09-07 02:06 UTC
i changed the &{} words but if i do not clean project,the app will display old words.
i open the resolved.xml , It generates a new result. but the app not show it ,need clean project

**Comment by nxnyk** [comment] 2023-09-07 02:12
i used com.android.tools.build:gradle:7.4.2 and Android Studio Electric Eel | 2022.1.1 Patch 2

**Comment by nxnyk** [comment] 2023-09-07 02:19
just build->clean project or rebuild project works 
file -> invalidate caches not works

**Comment by LikeTheSalad** [comment] 2023-09-07 11:51
I gave it a try though I couldn't reproduce the issue. In my case what I did was create these strings:

```xml
<resources>
    <string name="app_name">My Sample app</string>
    <string name="app_version">1.0.0</string>
    <string name="app_message">Some template with ${app_name}</string>
</resources>
```

And using `app_message` in a TextView. Then I compiled and the text view read: `Some template with My Sample app`.

Then I changed the template to:

```xml
<string name="app_message">Some template with ${app_version}</string>
```

Then re-compiled, where I saw the updated text view reading: `Some template with 1.0.0`.

---

I'm not sure if for your case you're re-compiling using some sort of "hot reload" mechanism which might not take resources into account.

In any case, we can take a deeper look at this issue if you could create your builds using the `--info` flag which will print extra compilation logs that could shed some light on what could be wrong. So if you could assemble your app 2 times, a fresh build and then a re-compile after changing a template, using the `--info` flag (for example: `./gradlew app:assembleDebug --info`), and provide me both logs, that'll help a lot to get to the root cause.

**Comment by LikeTheSalad** [comment] 2023-12-05 08:25
It's been a while so I'm going to close this for now, feel free to reopen it if the issue persists.

**Closed by LikeTheSalad** 2023-12-05 08:25 UTC
