### ISSUE TITLE
Getting task not found using Gradle and Gradle Plugin version 8.0

### ISSUE THREAD

**Issue by mtwarner** [LikeTheSalad/android-stem#41] opened 2023-05-18 11:18 UTC
Getting the following in my project:

> Could not create task ':myproj:commonStringFlavorDebugResourceLocator'.
   > Could not create task of type 'ResourceLocatorTask'.
      > Task with name 'generateFlavorDebugResValues' not found in project ':myproj'.

**Comment by LikeTheSalad** [comment] 2023-05-20 15:17
Thanks for your feedback @mtwarner - I couldn't reproduce it but, based on the error message you shared, I believe I have an idea of what's going on. So I've just released a new version, `2.4.1`, which might sort it out. 

If the new version still has this issue, I'm going to need a sample project where you are able to reproduce this issue to check it out locally.

**Comment by LikeTheSalad** [comment] 2023-08-15 13:32
I'm closing this, there's a newer version, `2.5.0` that adds support to AGP's 8.0.0+ for libraries.

**Closed by LikeTheSalad** 2023-08-15 13:32 UTC
