### ISSUE TITLE
resolved.xml not getting generated every other time

### ISSUE THREAD

**Issue by vvasilev92** [LikeTheSalad/android-stem#20] opened 2022-02-23 06:16 UTC
**Version:** 2.0.0

**Description:**
I am noticing that when building from Android Studio every other time the resolved folder disappears. I reproduce this every even time by hitting `Run 'app'` and I look at the generated/resolved folder.

This leads to strings in the app appearing with their literal placeholder names.

I also managed to end up in a situation where only some of the strings were generated but that seems to be rare and I can't reproduce it right now.

**Comment by LikeTheSalad** [comment] 2022-02-23 11:04
Hi @vvasilev92, the resolved folder should get emptied if there were changes made to the project's resources. This is to make sure that the resolved string are always up-to-date based on your templates.

When you say "This leads to strings in the app appearing with their literal placeholder names". Do you mean that you see the literal placeholder names in Android Studio's UI preview? Or in the installed app? Because Android Studio's preview behavior is not covered by this plugin so it can vary... What this plugin can guarantee is that the final build running in the app has the templates resolved, other than that, if they also show up as resolved in Android Studio's preview, that's just out of coincidence.

**Comment by vvasilev92** [comment] 2022-02-23 12:22
Yes. I am not talking about previews but installed app. I reproduce this every time. I am using a gradle plugin version of:

`        classpath 'com.android.tools.build:gradle:7.1.0'`

I will try it with a clean project.

**Comment by vvasilev92** [comment] 2022-02-24 08:38
@LikeTheSalad I made this repo - https://github.com/vvasilev92/LikeTheSaladTest
For me it's very easily reproducable that the string template does not work. If I run it consecutively from android studio, sometimes it's ok and shows the correct string substitution but some times I get:

![image](https://user-images.githubusercontent.com/91661923/155488636-74b86e68-dc99-4299-b70c-c37248df5af3.png)

**Comment by LikeTheSalad** [comment] 2022-02-24 10:53
Got it, thanks for the detailed info! I'm going to have a look by the end of the week because I can't right now, but in case you would like to make sure of always having the resolved strings, I'd recommend you to either do a clean->build... Or to manually run the resolver task, more info on that in the readme under "Running it manually". Based on what you described, it seems like some cache might be preventing the resolver task to run properly, that's why I proposed the above as temporary solution in case you need it.

**Comment by LikeTheSalad** [comment] 2022-05-16 08:23
Hi @vvasilev92, I just got chance to make updates here, it's been a couple of busy months. Though the issue you had should now be fixed on version 2.1.0, please feel free to reopen this ticket if you still running into this issue or a similar one :+1: 

Cheers,
Cesar

**Closed by LikeTheSalad** 2022-05-16 08:23 UTC
Labels: bug

**Comment by saeidkh6991** [comment] 2022-05-25 10:38
hi
I use version 2.1.1 but have the same problem with Gradle 7.4.2 but when downgraded to Gradle 7.3.3 it worked.

**Comment by LikeTheSalad** [comment] 2022-05-29 09:11
Hi @saeidkh6991, I tried running the tests with Android Plugin 7.2.0 and Gradle 7.4.2 and they passed. Please make sure to use the versions for both plugins as specified in Android's Gradle plugin version table here: https://developer.android.com/studio/releases/gradle-plugin#updating-gradle

If you keep seeing the issue, please let me know more details about your build.gradle configs, or if possible, provide a dummy project where the issue can be reproducible all the time.

**Comment by ankandrew** [comment] 2022-07-18 01:55
@LikeTheSalad What's happening to me is that to be 100% sure text is generating correctly, I have to do `Build > Clean Project`. Is this expected?

```
stem version: 2.1.1
gradle version: 7.2.1
```

**Comment by LikeTheSalad** [comment] 2022-07-18 05:58
Hi @ankandrew, when you say 100%, does it mean that when you don't do `Clean` you get some unresolved placeholders? Or the placeholders are being resolved but with the wrong values?

The way this plugin works is:
- It checks if there have been changes within your resource dirs.
- If there are changes, it runs the resolving process.
- If no changes are found, it should do nothing, this is to make sure that it doesn't do any extra work that's not needed and thus it doesn't add overhead process to your overall compilation.

So it shouldn't run unless you make changes to your resources, though probably if you happen to see that some newly added or changed placeholders aren't resolved, then it might be that Stem isn't recognizing those changes.

**Comment by ankandrew** [comment] 2022-07-18 20:17
@LikeTheSalad Thanks for the quick reply! I meant that sometimes I get unresolved placeholders when building normally and to be sure those placeholders are resolved **always**, I've to do `Build > Clean Project`. I haven't observed any pattern why this is happening though

**Comment by LikeTheSalad** [comment] 2022-07-20 06:08
I see, thanks for letting me know! It seems like there might be some sort of cache, not sure if Gradle or Android Studio related, that might be keeping the resolving process from running :( though I'd need to know how to reproduce it so that I can fix it. Otherwise I was thinking maybe to add some sort of config param that would make Stem run all the time, no matter if there are changes or not, it's not ideal, but might be useful in some cases I guess.
